name: 'ServiceNow CI/CD Install App'
description: 'Installs the specified application from the application repository onto the local instance.'
author: "ServiceNow"
inputs:
  version:
    description: "Application version to install"
    required: true
outputs:
  rollbackVersion:
    description: "Previously installed app's version, used to roll-back task"
runs:
  using: 'node12'
  main: './lib/index.js'
branding:
  icon: 'refresh-ccw'
  color: 'green'
